/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_darion_yaphet_examples_TestJNIArray */

#ifndef _Included_org_darion_yaphet_examples_TestJNIArray
#define _Included_org_darion_yaphet_examples_TestJNIArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_darion_yaphet_examples_TestJNIArray
 * Method:    mkString
 * Signature: ([Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_darion_yaphet_examples_TestJNIArray_mkString
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
