/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_darion_yaphet_examples_TestJNIPrimitive */

#ifndef _Included_org_darion_yaphet_examples_TestJNIPrimitive
#define _Included_org_darion_yaphet_examples_TestJNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_darion_yaphet_examples_TestJNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_darion_yaphet_examples_TestJNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
