/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_darion_yaphet_examples_TestJNIString */

#ifndef _Included_org_darion_yaphet_examples_TestJNIString
#define _Included_org_darion_yaphet_examples_TestJNIString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_darion_yaphet_examples_TestJNIString
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_darion_yaphet_examples_TestJNIString_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
